import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { HeartIcon, CartIcon, SearchIcon } from "./utils/icons";

export const metadata: Metadata = {
  title: "Lojinha",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "700", "600", "500"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-background">
        <div className="h-12 bg-slate-950 text-white  flex items-center justify-center ">
          Promoção de verão para todos os trajes de banho e entrega expressa
          grátis - OFF 50%!
        </div>
        <header className="border-b   border-slate-950/60 ">
          <div className="w-full max-w-7xl mx-auto flex items-center justify-between h-28">
            <div className="brand text-2xl font-bold">Logo Marca</div>
            <nav>
              <ul className="flex text-base gap-8">
                <li>Home</li>
                <li>Contato</li>
                <li>Sobre</li>
                <li>Cadastrar</li>
              </ul>
            </nav>
            <div className="flex gap-4">
              <div className="flex gap-4 ">
                <input
                  className="text-xs w-full min-w-48"
                  type="text"
                  placeholder="O que você está procurando?"
                />
                <SearchIcon size={30} />
              </div>

              <HeartIcon size={30} />
              <CartIcon size={30} />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
